### ISSUE TITLE
errors when running aqcc hello.c

### ISSUE THREAD

**Issue by WilliamWangPeng** [ushitora-anqou/aqcc#15]
Hi dear author,  
I find some errors here, do you know why?
![image](https://user-images.githubusercontent.com/51076736/119540838-7937c280-bdc0-11eb-88c7-e2a35058e79c.png)

thank you  
best regards  
William

**Comment by ushitora-anqou** [comment]
`#include <stdio.h>` is not supported in aqcc.

The following code:
```c
int printf(const char *format, ...);
int main()
{
    printf("hi\n");
    return 0;
}
```
should work with `./aqcc hello.c stdlib.c -o hello` (but not tested)

**Comment by zylinux** [comment]
I had same issue, so I compiled it with stdlib.c system.s it works. @ushitora-anqou I have tested it
maintest.c:
int main(int argc, char** argv)
{
	int a;
	a=10;
	return a;
}

./aqcc maintest.c cc/stdlib.c cc/system.s -o hello

./hello

echo $?
10

**Comment by ushitora-anqou** [comment]
Thanks! I'll close this issue.

**Comment by zylinux** [comment]
@ushitora-anqou  I was looking for your contact information email etc, but i did not see any. 
May I make a friend with since I am really interested in compiler. would like to discuss some questions with you.
my email address is 
zhangmin1984121@gmail.com 
if you dont mind would you shoot me an email ?

thanks a lot.

**Comment by zylinux** [comment]
was looking for your email address want to make friend with you and discuss
this aqcc more .

**Comment by zylinux** [comment]
the funny part was. many of the website you on, written by Japanese. I was trying to read the Japanese, but cannot understand. lol

**Comment by ushitora-anqou** [comment]
@zylinux My email address is ushitora@anqou.net, and my Twitter account is [ushitora_anqou](https://twitter.com/ushitora_anqou). Or, if you want to discuss aqcc, feel free to make a new issue or discussion on this GitHub repo.

**Comment by zylinux** [comment]
For Aqcc what is the future plan for this project ? any plan ?
